%YAML 1.2
---
processed_data_home: ../cocoa/processed # where processed data lives
output_home: ./output # where you can find trained models

model_config: ./config/model/llama-32-lite.yaml
max_seq_len: !!int &max_len 4096
n_epochs: !!int 2
run_name: &run_name cotorra-t-rope

wandb:
  project: cotorra
  run_name: *run_name

custom_loss: !!bool true
quantile_token_loss:
  qt_weight: !!float 20.0
label_weighted_loss:
  tokens_of_interest:
    - XFR-IN//icu
    - RESP//imv
    - DSCG//expired
    - DSCG//hospice
  toi_weight: !!float 20.0

time_based_rope:
  sec_per_pos_id: !!int 300

training_args:
  report_to: wandb
  run_name: *run_name
  per_device_train_batch_size: !!int 8
  per_device_eval_batch_size: !!int 8
  save_total_limit: !!int 1
  metric_for_best_model: eval_loss
  load_best_model_at_end: !!bool true
  greater_is_better: !!bool false
  eval_strategy: steps
  prediction_loss_only: !!bool true # may improve training speed
  save_strategy: best
  ddp_find_unused_parameters: !!bool false
  neftune_noise_alpha: !!float 5.0
  auto_find_batch_size: !!bool false # turning this on may cause issues with hyperparameter tuning
  learning_rate: !!float 2e-4
  gradient_accumulation_steps: !!int 1
  remove_unused_columns: !!bool false # otherwise `s_elapsed` is automatically dropped
  # max_steps: !!int 10 # uncomment for testing purposes only
  bf16: !!bool true

tuning_args:
  direction: minimize
  backend: optuna
  n_trials: !!int 3

extract:
  max_len: *max_len
  batch_size: !!int 64
  time_limit_s: !!int 86400 # 24 hours

score:
  max_len: *max_len
  n_samp: !!int 5 # MC samples per input per trajectory type
  target_tokens: # token-based outcomes of interest
    - XFR-IN//icu
    - DSCG//expired
    - RESP//imv
  end_tokens: # tokens that naturally terminate a sequence
    - EOS
  suppressed_tokens: [] # tokens to suppress (e.g. PAD) via logit bias
  trunc_id: !!int 0 # token id to force after time horizon exceeded
  max_time: !!int 1440 # 1 day, max time horizon in minutes
  batch_size: !!int 64
