%YAML 1.2
---
processed_data_home: ~/paper_fast/new/standpipe/lib/cocoa/cocoa/processed # where processed data lives
output_home: ./output/mimic # where you can find trained models

model_config: ./config/model/llama-32-lite.yaml
max_seq_len: !!int &max_len 4096
n_epochs: !!int 2
run_name: &run_name cotorra-tuning

tokens_of_interest: &tois
  - XFR-IN//icu
  - RESP//imv
  - DSCG//expired
  - DSCG//hospice
  - XFR-IN//icu
  - RESP//imv
  - DSCG//expired
  - DSCG//hospice
  - LAB-RES//sodium_Q0
  - LAB-RES//sodium_Q9
  - LAB-RES//potassium_Q0
  - LAB-RES//potassium_Q9
  - LAB-RES//hemoglobin_Q0
  - LAB-RES//glucose_serum_Q0
  - VTL//heart_rate_Q9
  - SOFA//resp-4
  - SOFA//renal-4
  - SOFA//liver-4
  - SOFA//cv-4
  - ASMT//cam_total_yes

wandb:
  project: cotorra
  run_name: *run_name

custom_loss: !!bool true
quantile_token_loss:
  qt_weight: !!float 20.0
  kernel:
    type: "cubic"
    factor: 1.0 # keep in [0,1] for cubic or (0,1) for atanh
    order: "loss_first"
    loss_type: "mse"
# label_weighted_loss:
#   tokens_of_interest: *tois
#   toi_weight: !!float 20.0

time_based_rope:
  sec_per_pos_id: !!int 300

training_args:
  report_to: wandb
  run_name: *run_name
  per_device_train_batch_size: !!int 8
  per_device_eval_batch_size: !!int 8
  save_total_limit: !!int 1
  metric_for_best_model: eval_loss
  load_best_model_at_end: !!bool true
  greater_is_better: !!bool false
  eval_strategy: steps
  prediction_loss_only: !!bool true # may improve training speed
  save_strategy: best
  ddp_find_unused_parameters: !!bool false
  neftune_noise_alpha: !!float 5.0
  auto_find_batch_size: !!bool false # turning this on may cause issues with hyperparameter tuning
  learning_rate: !!float 2e-4
  gradient_accumulation_steps: !!int 1
  remove_unused_columns: !!bool false # otherwise `s_elapsed` is automatically dropped
  bf16: !!bool true
  # max_steps: !!int 10 # uncomment for testing purposes only

tuning_args:
  direction: minimize
  backend: optuna
  n_trials: !!int 5

extract:
  max_len: *max_len
  batch_size: !!int 64
  shard_size: !!int 10000 # number of samples per shard when saving extracted features

score:
  max_len: *max_len
  n_samp: !!int 10 # MC samples per input per trajectory type
  target_tokens: *tois # token-based outcomes of interest
  end_tokens: # tokens that naturally terminate a sequence
    - EOS
  suppressed_tokens: [] # tokens to suppress (e.g. PAD) via logit bias
  trunc_id: !!int 0 # token id to force after time horizon exceeded
  max_time: !!int 1440 # 1 day, max time horizon in minutes
  batch_size: !!int 64
